-- MySQL Script generated by MySQL Workbench
-- Mon 17 Apr 2023 07:45:04 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbproy1sopes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbproy1sopes` ;

-- -----------------------------------------------------
-- Schema dbproy1sopes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbproy1sopes` ;
USE `dbproy1sopes` ;

-- -----------------------------------------------------
-- Table `dbproy1sopes`.`Voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproy1sopes`.`Voto` ;

CREATE TABLE IF NOT EXISTS `dbproy1sopes`.`Voto` (
  `idVoto` INT NOT NULL AUTO_INCREMENT,
  `sede` INT NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(100) NOT NULL,
  `papeleta` VARCHAR(100) NOT NULL,
  `partido` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVoto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'sopesuser'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON dbproy1sopes.* TO 'sopesuser'@'localhost';
ALTER USER 'sopesuser'@'localhost' IDENTIFIED BY 'fullstack';
