version: '3.8'

services:
  
  mysql:
    image: serchiboi/proy1_dbmysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: fullstack
      MYSQL_USER: sopesuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbproy1sopes
