FROM golang:1.15
# Seteamos el work directory
WORKDIR /app

# Download the dependencies
RUN go mod download
# Import the gorilla library
RUN go get -u github.com/gorilla/mux

# Import the MySQL driver
RUN go get -u github.com/go-sql-driver/mysql

COPY . .
RUN go build -o main


EXPOSE 8080
CMD ["./main"]