version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: serchiboi/pub_redis:latest
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: 34.29.189.230
