FROM ubuntu:20.04

# Instalar dependencias
# RUN sudo apt-get update && \
#     sudo apt install gcc && \
#     sudo apt install -y build-essential && \
#     sudo apt-get install manpages-dev

COPY cpu_202000194.c .

# RUN gcc -o cpu_202000194 cpu_202000194.c

COPY ram_202000194.c .

# RUN gcc -o ram_202000194 ram_202000194.c3.

# Agregar permisos al usuario
# RUN chown -R root:root /usr/src/sysinfo.c && \
#     chmod 644 /usr/src/sysinfo.c && \
#     chmod +x /usr/src/sysinfo



