version: '3'
services:
  backend:
    container_name: "api_practica2_202000194"
    image: alvarosp24/api_practica2_202000194
    build:
      context: ./api
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app_work
  frontend:
    container_name: "frontend_practica2_202000194"
    image: alvarosp24/frontend_practica2_202000194
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_work
networks:
  app_work:
    driver: bridge

# docker login
# docker tag mi-imagen mi-usuario/mi-repo
# docker tag api_practica2_202000194 alvarosp24/api_practica2_202000194
# docker push mi-usuario/mi-repo
