version: '3'
services:
  backend:
    container_name: "backend_practica2_202000194"
    image: alvarosp24/backend_practica2_202000194
    build:
      context: ./api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_work
  frontend:
    container_name: "frontend_practica2_202000194"
    image: alvarosp24/frontend_practica2_202000194
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_work
networks:
  app_work:
    driver: bridge
