version: '3'
services:
  frontend:
    build:
      context: ./sopesprac1
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./BackendGo
    ports:
      - "8000:8000"
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: