apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: fullstack
            - name: MYSQL_USER
              value: sopesuser
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: dbproy1sopes
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: proyecto
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: LoadBalancer
  loadBalancerIP: 35.188.106.165
  