apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis 
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: proyecto
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: LoadBalancer
  loadBalancerIP: 34.136.99.148
  