version: '3'
services:
  backend:
    container_name: "backend_practica1_202000194"
    image: alvarosp24/backend_practica1_202000194
    build:
      context: ./BackendGo
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./Ejecscript:/scripts
    depends_on:
      - db
    networks:
      - app_work
  frontend:
    container_name: "frontend_practica1_202000194"
    image: alvarosp24/frontend_practica1_202000194
    build:
      context: ./sopesprac1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_work
  db:
    container_name: "db_practica1_202000194"
    platform: linux/x86_64
    build: ./database
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 2412
      MYSQL_ROOT_PASSWORD: 2412
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_work
  ejecscript:
    container_name: "script_practica1_202000194"
    image: alvarosp24/script_practica1_202000194
    restart: always
    build: ./Ejecscript
    volumes:
      - ./Ejecscript:/scripts
    command: ["bash", "/scripts/ejec.sh"]
    networks:
      - app_work
networks:
  app_work:
    driver: bridge
volumes:
  mysql-data:
