version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: serchiboi/proy1_api:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: 34.29.189.230
      MYSQL_HOST: 34.133.55.208
