FROM mysql:8
# were gonna copy our  database migrations file
COPY ./database/*.sql
# Set environment variables for the database
ENV MYSQL_DATABASE=mydb \
    MYSQL_USER=myuser \
    MYSQL_PASSWORD=mypassword \
    MYSQL_ROOT_PASSWORD=rootpassword

# Copy the database initialization script
COPY init.sql /docker-entrypoint-initdb.d/